
---

  - name: Install Helm
    become: true
    get_url:
      url:  https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
      dest: /home/ubuntu/helm-v2.14.3-linux-amd64.tar.gz

  # create Helm directory 
  - name: create Helm directory 
    file:
      path:  /home/ubuntu/Helm
      state: directory

  # untar helm 
  - name: Extract archive
    become: true
    unarchive:
      src: /home/ubuntu/helm-v2.14.3-linux-amd64.tar.gz
      dest: /home/ubuntu/Helm
           
  # move Helm to /usr/local/bin/helm
  - name: move Helm /usr/local/bin/Helm
    become: yes
    copy:
      src: /home/ubuntu/Helm/linux-amd64/helm
      dest: /usr/local/bin/helm
      mode: a+x







