---
  - name: Install Tilt
    become: true
    get_url:
      url:  https://github.com/windmilleng/tilt/releases/download/v0.10.10/tilt.0.10.10.linux.x86_64.tar.gz
      dest: /home/ubuntu/tilt.0.10.8.linux.x86_64.tar.gz

  # create tilt directory 
  - name: create tilt directory 
    file:
      path:  /home/ubuntu/Tilt
      state: directory

  # untar Tilt
  - name: Extract archive
    become: true
    unarchive:
      src: /home/ubuntu/tilt.0.10.8.linux.x86_64.tar.gz
      dest: /home/ubuntu/Tilt
           
  # move Tilt to /usr/local/bin/tilt
  - name: move tilt /usr/local/bin/tilt
    become: yes
    copy:
      src: /home/ubuntu/Tilt/tilt
      dest: /usr/local/bin/tilt
      mode: a+x

